"""empty message

Revision ID: 3c72e974eb71
Revises: 
Create Date: 2023-04-10 14:07:22.802830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c72e974eb71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('bedrooms', sa.String(length=10), nullable=True),
    sa.Column('bathrooms', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.Column('photo', sa.String(length=260), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
